from .bright import Bright, BrightWidget
from .ramp import Ramp, RampWidget
from .concentric_grating import ConcentricGrating, ConcentricGratingWidget
from .dark import Dark, DarkWidget
from .dot import Dot, DotWidget
from .image import Image, ImageWidget
from .looming import Looming, LoomingWidget
from .okr import OKR, OKR_Widget
from .omr import OMR, OMR_Widget
from .phototaxis import Phototaxis, PhototaxisWidget
from .prey_capture import PreyCapture, PreyCaptureWidget
