from .protocol_item import RampType
from daq_tools import BoardType

DEFAULT = {
    'foreground_color': (0.2, 0.2, 0.2, 1.0),
    'background_color': (0.0, 0.0, 0.0, 1.0),
    'phototaxis_polarity': 1,
    'omr_spatial_period_mm': 5,
    'omr_angle_deg': 0,
    'omr_speed_mm_per_sec': 10,
    'concentric_spatial_period_mm': 5,
    'concentric_speed_mm_per_sec': 10,
    'okr_spatial_frequency_deg': 20,
    'okr_speed_deg_per_sec': 36,
    'looming_center_mm': (0,0),
    'looming_period_sec': 10,
    'looming_expansion_time_sec': 10,
    'looming_expansion_speed_mm_per_sec': 10,
    'dot_center_mm': (0.0, 0.0),
    'dot_radius_mm': 1.0,
    'n_preys': 50,
    'prey_speed_mm_s': 0.75,
    'prey_radius_mm': 0.25,
    'ramp_duration_sec': 1.0,
    'ramp_powerlaw_exponent': 0.33,
    'ramp_type': RampType.LINEAR,
    'image_path': 'ZebVR/resources/checkerboard.png',
    'image_res_px_per_mm': 43,
    'image_offset_mm': (0,0),
    'frequency_Hz': 440.0,
    'amplitude_dB': 60.0,
    'audio_ramp_start_Hz': 440.0,
    'audio_ramp_stop_Hz': 880.0,
    'audio_ramp_duration_sec': 1.0,
    'audio_ramp_powerlaw_exponent': 1.67,
    'audio_ramp_type': RampType.LOG,
    'click_rate': 10.0,
    'click_duration': 0.01,
    'click_polarity': 0,
    'audio_file_path': 'ZebVR/resources/danionella_cerebrum_pnas.2314017121.wav',
    'daq_DO_channel': [0],
    'daq_ttl_duration_msec': 10,
    'daq_type': BoardType.ARDUINO,
    'daq_board_id': '/dev/ttyACM0'
}