from .protocol_item import RampType

DEFAULT = {
    'foreground_color': (0.2, 0.2, 0.2, 1.0),
    'background_color': (0.0, 0.0, 0.0, 1.0),
    'phototaxis_polarity': 1,
    'omr_spatial_period_mm': 5,
    'omr_angle_deg': 0,
    'omr_speed_mm_per_sec': 10,
    'concentric_spatial_period_mm': 5,
    'concentric_speed_mm_per_sec': 10,
    'okr_spatial_frequency_deg': 20,
    'okr_speed_deg_per_sec': 36,
    'looming_center_mm': (0,0),
    'looming_period_sec': 10,
    'looming_expansion_time_sec': 10,
    'looming_expansion_speed_mm_per_sec': 10,
    'dot_center_mm': (0.0, 0.0),
    'dot_radius_mm': 1.0,
    'n_preys': 50,
    'prey_speed_mm_s': 0.75,
    'prey_radius_mm': 0.25,
    'brightness_start_percent': 0.0,
    'brightness_stop_percent': 100.0,
    'brightness_ramp_duration_sec': 1.0,
    'brightness_ramp_log_curvature': 10,
    'brightness_ramp_powerlaw_exponent': 2,
    'brightness_ramp_type': RampType.LOG,
    'frequency_start_Hz': 440.0,
    'frequency_stop_Hz': 880.0,
    'frequency_ramp_duration_sec': 1.0,
    'frequency_ramp_type': RampType.LOG,
    'image_path': 'ZebVR/resources/checkerboard.png',
    'image_res_px_per_mm': 43,
    'click_rate': 10.0,
    'click_amplitude': 0.5,
    'click_duration': 0.01,
    'click_polarity': 0,
    'frequency_Hz': 1_000.0,
    'amplitude_dB_SPL': 60.0,
    'image_offset_mm': (0,0),
}